name: "Pantheon Rsync"
description: "This GitHub Action builds your assets"
author: "irishdistillers"
inputs:
  THEME_DIRECTORY:
    description: "Directory where the them to sync is located."
    required: true
  REMOTE_REPO_NAME:
    description: "Remote GIT Repo Name"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
